using System;
using System.Collections.Generic;
using System.Text;

namespace PwF.Enums
{
    public enum classes
    {
        Barbarian,
        Bard,
        Cleric,
        Druid,
        Fighter,
        Monk,
        Paladin,
        Ranger,
        Rogue,
        Sorcerer,
        Wizard,
        Alchemist,
        Cavalier,
        Gunslinger,
        Inquisitor,
        Megus,
        Ninja,
        Oracle,
        Samurai,
        Summoner,
        Witch,
        Arcanist,
        Bloodrager,
        Brawler,
        Hunter,
        Investigator,
        Shaman,
        Skald,
        Slayer,
        Swashbuckler,
        Warpiest,
        Kinaticist,
        Medium,
        Meanerist,
        Occultist,
        Psychic,
        Spiritualist,
        ArchaneArcher,
        ArchaneTrickster,
        Assassin,
        BattleHerald,
        DragonDisciple,
        Duelist,
        EldrichKnight,
        HolyVindicator,
        HorizonWalker,
        Loremaster,
        MasterChymist,
        MasterSpy,
        MysticTheurge,
        NatureWarden,
        PathfindChronicler,
        RageProphet,
        ShadowDancer,
        StalwartDefender,
    }
}
